project:
  type: website
  output-dir: docs

website:
  title: "Mary Kreklow"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: rtip.qmd
      - sidebar:maps
      - file: mini_project2.qmd
      - file: RATATOUILLE.qmd
      - file: FinalProject.qmd

  sidebar:
    - id: maps
      title: "Maps Project"
      contents:
        - us_states.qmd
        - wi_gerrymandering.qmd
 
  page-footer:
    left: |
      &copy; Mary Kreklow, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual


