project:
  type: website
  output-dir: docs

website:
  title: "Mary Kreklow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - hw.qmd
      - sidebar:maps

  sidebar:
    - id: maps
      title: "Maps"
      contents:
        - us_states.qmd
        - wi_gerrymandering.qmd
 
  page-footer:
    left: |
      &copy; Mary Kreklow, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual


