project:
  type: website
  output-dir: docs

website:
  title: "Mary Kreklow"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
    menu:
      - text: Source Code
        url:  https://code.com
      - text: Report a Bug
        url:  https://bugs.com
        
 page-footer:
    left: |
      &copy; Mary Kreklow, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

