project:
  type: website
  output-dir: docs

website:
  title: "Mary Kreklow"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - sidebar:Data Science 2


  sidebar:
    - id: Data Science 2
      title: "Projects from MSCS 264"
      contents:
        - us_states.qmd
        - wi_gerrymandering.qmd
        - rtip.qmd
        - mini_project2.qmd
        - RATATOUILLE.qmd

  page-footer:
    left: |
      &copy; Mary Kreklow, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    code-overflow: wrap

editor: visual


